name: gen image

on:
  workflow_dispatch:

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Build image
      run: docker build -t zabbix-sql-tun .
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_ACTOR }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - 
      name: Push to Docker Hub
      run: |
        docker image tag zabbix-sql-tun:latest dzhunli/zabbix-sql-tun:latest
            docker push dzhunli/zabbix-sql-tun:latest
